apiVersion: v2
name: binarycat-polaris-bootstrap
description: Bootstrap Root User job for Apache Polaris catalog
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - polaris
  - apache
  - iceberg
home: https://github.com/binarycat0/helm-charts-demo-polaris-bootstrap-job
sources:
  - https://github.com/binarycat0/helm-charts-demo-polaris-bootstrap-job
maintainers:
  - name: binarycat0
